meta_title: "Destinosé"
meta_description: "The one web-app that allows you to intelligently pick your next travel destination based on things you like most"
meta_image: "bg-landing.jpg"
twitter_account: "@Destinosé"
